#!/usr/bin/env bash
# install nginx web server
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install nginx
service start nginx
sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
sudo rm /var/www/html/index.nginx-debian.html
