#!/usr/bin/env bash
# a script that configures HAproxy in a load balancer 

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
sudo chown -R $USER:$USER /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 10564-web-01 52.91.122.100:80 check\n\tserver 10564-web-02 34.239.250.161:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
