#!/usr/bin/env bash
# Script that sets the port 80
# sudo nginx status returns 'not running'; netstat -lpn does not show port 80
# Solution:
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart